sudo: false
language: node_js
dist: trusty
node_js:
  - 'stable'
  - '8'
  - '6'
addons:
  apt:
    packages:
      - libav-tools
before_script:
  - ffplay -vn -hide_banner -stats -nodisp -autoexit 440-hz.ogg
